mandatoryAccounts:
  # We recommend you do not change mandatory account names. These are used within Landing Zone Accelerator to reference the accounts from other config files.
  # The "name" value does not currently support spaces
  # The "name" value DOES NOT need to match the account name
  - name: Management
    description: The management (primary) account. Do not change the name field for this mandatory account. Note, the account name key does not need to match the AWS account name.
    email: "gjunlin@dsta.gov.sg"
    organizationalUnit: Root
  - name: LogArchive
    description: The log archive account. Do not change the name field for this mandatory account. Note, the account name key does not need to match the AWS account name.
    email: "tanyishengalvan+awslzalogarchive@gmail.com"
    organizationalUnit: Security
  - name: Audit
    description: The security audit account (also referred to as the audit account). Do not change the name field for this mandatory account. Note, the account name key does not need to match the AWS account name.
    email: "tanyishengalvan+awslzaaudit@gmail.com"
    organizationalUnit: Security
workloadAccounts:
  # The "name" will be used to set the AWS Account name
  # The "name" value does not currently support spaces
  # The "name" value DOES NOT need to match the account name
  - name: Network
    description: The network account. Do not change the name field for this account. Note, the account name key does not need to match the AWS account name.
    email: "tanyishengalvan+awslzanetwork@gmail.com"
    organizationalUnit: Infrastructure
  - name: SharedServices
    description: The Shared services account. Do not change the name field for this account. Note, the account name key does not need to match the AWS account name.
    email: "tanyishengalvan+awslzasharedservices@gmail.com"
    organizationalUnit: Infrastructure
  - name: user1
    description: Suspended account
    email: "awsrampupuser1@example.com"
    organizationalUnit: Suspended
  - name: user2
    description: Suspended account
    email: "awsrampupuser2@example.com"
    organizationalUnit: Suspended
  - name: user3
    description: Suspended account
    email: "user3@awsrampup.com"
    organizationalUnit: Suspended
  - name: user4
    description: Suspended account
    email: "user4@awsrampup.com"
    organizationalUnit: Suspended
  - name: user5
    description: Suspended account
    email: "user5@awsrampup.com"
    organizationalUnit: Suspended
  - name: user6
    description: Suspended account
    email: "user6@awsrampup.com"
    organizationalUnit: Suspended
  - name: user7
    description: Suspended account
    email: "user7@awsrampup.com"
    organizationalUnit: Suspended
  - name: user8
    description: Suspended account
    email: "user8@awsrampup.com"
    organizationalUnit: Suspended
  - name: user9
    description: Suspended account
    email: "user9@awsrampup.com"
    organizationalUnit: Suspended
